version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- ps: Push-Location ./tests;
- ps: ./build.ps1 -Script "./tests.cake" -Verbosity Diagnostic;
- ps: Pop-Location
- ps: nuget pack ./Cake.Sitecore.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
- path: Cake.Sitecore.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 1HzwRb3PHuaHzBBykf7IkMjI7wsF1nW99/Wb15n2rp+GgCKiNkD9MyoznK5zAdqa
  skip_symbols: true
  on:
    branch: master
